version: 2.1

jobs:
  build:
    steps:
      - checkout
      - run:
          name: build
          command: docker build -t johnsnch/ruby:2.1.2
      - run:
          name: verify
          command: |
            docker run --rm johnsonch/ruby:2.1.2 \
            bash -c 'ruby --version'
